credentials: &credentials
  provider: AWS
  region: us-east-1
  aws_access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  path_style: true
  aws_signature_version: 4

development:
  <<: *credentials
  endpoint: <%= ENV['S3_ENDPOINT'] || 'http://s3:9000' %>
  bucket: ka-dev
  # don't panic, these are fake (see docker-compose.yml)
  aws_access_key_id: AKIAIOSFODNN7EXAMPLE
  aws_secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

test:
  provider: Local
  local_root: <%= Rails.root.join 'tmp' %>
  bucket: ka-test

production:
  <<: *credentials
  host: s3.kleine-anfragen.de
  bucket: ka-prod