class CreatePaperRelations < ActiveRecord::Migration
  def change
    create_table :paper_relations do |t|
      t.references :paper, index: true, foreign_key: true, null: false
      t.integer :other_paper_id, index: true, null: false
      t.string :reason

      t.timestamps null: false
    end

    add_foreign_key :paper_relations, :papers, column: :other_paper_id

    # has a shorter name, because the autogenerated one is over 63 chars
    add_index :paper_relations, [:paper_id, :other_paper_id, :reason], name: 'index_paper_relations_on_p_and_other_p_and_reason', unique: true
  end
end
